version: "2.1"
networks:
  internal_network:
services:
  724_http-proxy:
    restart: always
    networks:
      - internal_network
    image: 724_http-proxy:node20
    container_name: 724_http-proxy
    logging:
      driver: "json-file"
      options:
        max-size: "300k"
        max-file: "3"
    volumes:
      - ./data:/node_/data
    environment:
      - "DOMAIN_NAME=www.gjxt.xyz"
      - "username=gjxt"
      - "password="
      - "ADMIN_PORT=8444"
      - "ADMIN_HTTP_MODE=true"
      - "DDNS_INTERVAL=300"
      - "http_proxy_domains=www.gjxt.xyz"
      - "http_proxy_protocols=https:"
      - "http_proxy_paths=/"
      - "http_proxy_hosts=im1c5366d.7x24cc.com"
      - "http_proxy_ports=443"
      - "http_proxy_pretends=true"
      - "http_proxy_redirects=false"
      - "ws_proxy_domains=www.gjxt.xyz"
      - "ws_proxy_protocols=wss:"
      - "ws_proxy_paths=/"
      - "ws_proxy_hosts=yw.msa.gov.cn"
      - "ws_proxy_ports=443"
    expose:
      - "20022"
      - "8443"
      - "443"
      - "80"
    ports:
      - "8443:8443"
      - "8444:8444"
      - "443:443"
      - "80:80"
